name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/checkout@main
        with:
          host: ${{ secrets.STUDY_IP }}
          username: ${{ secrets.STUDY_SSH_ID}}
          key: ${{ secrets.STUDY_SSH_KEY }}
          port: ${{ secrets.STUDY_SSH_PORT }}
      - run: ls
      - run: ls -al
      - run: chmod 777 node.sh
      - run: ./node.sh
